import Head from 'next/head';
import styles from '../styles/home.module.css';
import Navbar from './components/Navbar';
import Button from '@mui/material/Button';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenidos<a href='./'> Kevin Redlich Book</a>
        </h1>
        <div className={styles.btn}>
          <Button sx={{ m: 1 }} size='large' variant='outlined'>
            <Link href='/posts/'>Posts</Link>
          </Button>
          <Button sx={{ m: 1 }} size='large' variant='outlined'>
            <Link href='/users/'>Users</Link>
          </Button>
        </div>
      </main>
    </div>
  );
}
